version: '3.8'

services:
  nexus_service:
    container_name: dependenciesmanagment-nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - store:/data
    networks:
      - rede1
  
networks:
  rede1:
    driver: bridge

volumes:
  store:
    driver: local    