version: '3.8'

services: 
  mailhog_service:
    container_name: smtp-server-mailhog
    image: mailhog/mailhog:v1.0.1
    ports: 
      -  '1025:1025'
      -  '8025:8025' 
    volumes:
      - store:/data
    networks:
      - rede1
    
networks:
  rede1:
    driver: bridge

volumes:
  store:
    driver: local