scrape_configs:
 - job_name: 'prometheus'
 scrape_interval: 5s
 static_configs:
  - targets: ['localhost:8080', 'localhost:9090', 'localhost:9100', 'localhost:9113']

 - job_name: 'bff'
 metrics_path: '/actuator/prometheus'
 scrape_interval: 2s
 static_configs:
  - targets: ['localhost:8080']
  labels:
   application: 'bff'