
services:

  grafana:
    image: grafana/grafana:latest
    container_name: container-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - store:/data
    networks:
      - rede1

networks:
  rede1:
    external: true

volumes:
  store:
    driver: local