version: '3.8'
services:
  rabbitmq_service:
    image: rabbitmq:3-management-alpine
    container_name: 'streaming-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - store:/data/:/var/lib/rabbitmq/
        - store:/log/:/var/log/rabbitmq
    networks:
        - rede1

networks:
  rede1:
    external: true

volumes:
  store:
    driver: local    