
version: '3.7'
services:

  elasticsearch:
    container_name: container-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-store:/usr/share/elasticsearch/data
    networks:
      - rede1
      
  kibana:
    container_name: container-kibana
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - rede1
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-store:
    driver: local

networks:
  rede1:
    external: true