version: '3.8'

services: 
  minio_service:
    container_name: filestorage-minio
    image: docker.io/bitnami/minio:2022
    environment: 
      -  MINIO_ROOT_USER=user
      -  MINIO_ROOT_PASSWORD=12345678
      -  MINIO_DEFAULT_BUCKETS=miniobucket
    ports: 
      -  '9000:9000'
      -  '9001:9001' 
    volumes:
      - store:/data
    networks:
      - rede1
    
networks:
  rede1:
    driver: bridge

volumes:
  store:
    driver: local  