version: "3.8"

services:

  minio:
    image: minio/minio:latest
    container_name: filestorage-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: "12345678"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - store:/data
    networks:
      - rede1

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 user 12345678 &&
      mc mb local/miniobucket &&
      mc anonymous set download local/miniobucket &&
      exit 0;
      "
    networks:
      - rede1

networks:
  rede1:
    driver: bridge

volumes:
  store:
    driver: local