version: '3.8'

services:
  zookeeper_service:
    container_name: server-zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - rede1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_service:
    container_name: streaming-kafka
    image: confluentinc/cp-kafka:latest
    networks: 
      - rede1
    depends_on:
      - zookeeper_service
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: server-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://streaming-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop_service:
    container_name: gui-kafka
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 19000:9000
    depends_on:
      - kafka_service 
    networks: 
      - rede1
    environment:
      KAFKA_BROKERCONNECT: streaming-kafka:29092

networks: 
  rede1:
    driver: bridge  
