version: '3.8'
services:
  postgres_service:
    container_name: database-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - store:/data
    networks:
      - rede1  

networks:
  rede1:
    driver: bridge

volumes:
  store:
    driver: local     