version: '3.8'

services:
  mongodb_service:
    container_name: database-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - store:/data
    networks:
      - rede1

networks:
  rede1:
    external: true

volumes:
  store:
    driver: local     