version: '3.8'
services:
  redis_service:
    container_name: database-redis
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - store:/data
    networks:
      - rede1    

networks:
  rede1:
    external: true

volumes:
  store:
    driver: local     